### ISSUE TITLE
No option to include non-empty directories

### ISSUE THREAD

**Issue by brentonhouse** [npm/ignore-walk#3] opened 2018-01-19 15:47 UTC
While I can include empty directories using the option `includeEmpty`, there is no option for including non-empty directories.

I am trying to use this as a filter with `fs-extra.copy()` but because the directory itself is not included,  all sub-directories and files are excluded.   I've tried setting `includeEmpty` to true but that does not include directories that contain files or other directories.

It's a small change and I don't mind creating a PR.  I just wanted to see if this be something you would be good with.

Changing this to be the default would also make the output compatible with `wrench.readdirRecursive()`

**Comment by isaacs** [comment] 2018-03-25 18:03
By default, it only includes files on the list, not directories.  This matches the intended behavior for programs like git and npm that track files for inclusion in an archive of some sort.

It sounds like what you want is a way to emit entries for all directories walked, even if they have no files included.  Using this would imply `includeEmpty`, I suppose.

I'm not opposed to adding that option.  Patch welcome, please include docs and tests :)

**Comment by wraithgar** [comment] 2023-11-28 21:19
Closing this one due to age.

**Closed by wraithgar** 2023-11-28 21:19 UTC
